// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: zk.proto

#include "zk.pb.h"
#include "zk.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace masterworker {

static const char* MasterWorker_method_names[] = {
  "/masterworker.MasterWorker/sendAliveRequest",
};

std::unique_ptr< MasterWorker::Stub> MasterWorker::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MasterWorker::Stub> stub(new MasterWorker::Stub(channel));
  return stub;
}

MasterWorker::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sendAliveRequest_(MasterWorker_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MasterWorker::Stub::sendAliveRequest(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::masterworker::AliveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sendAliveRequest_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::masterworker::AliveResponse>* MasterWorker::Stub::AsyncsendAliveRequestRaw(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::masterworker::AliveResponse>::Create(channel_.get(), cq, rpcmethod_sendAliveRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::masterworker::AliveResponse>* MasterWorker::Stub::PrepareAsyncsendAliveRequestRaw(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::masterworker::AliveResponse>::Create(channel_.get(), cq, rpcmethod_sendAliveRequest_, context, request, false);
}

MasterWorker::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterWorker_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterWorker::Service, ::masterworker::AliveRequest, ::masterworker::AliveResponse>(
          std::mem_fn(&MasterWorker::Service::sendAliveRequest), this)));
}

MasterWorker::Service::~Service() {
}

::grpc::Status MasterWorker::Service::sendAliveRequest(::grpc::ServerContext* context, const ::masterworker::AliveRequest* request, ::masterworker::AliveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace masterworker

