// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: zk.proto
#ifndef GRPC_zk_2eproto__INCLUDED
#define GRPC_zk_2eproto__INCLUDED

#include "zk.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace masterworker {

class MasterWorker final {
 public:
  static constexpr char const* service_full_name() {
    return "masterworker.MasterWorker";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Ping
    virtual ::grpc::Status sendAliveRequest(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::masterworker::AliveResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::AliveResponse>> AsyncsendAliveRequest(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::AliveResponse>>(AsyncsendAliveRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::AliveResponse>> PrepareAsyncsendAliveRequest(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::AliveResponse>>(PrepareAsyncsendAliveRequestRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::AliveResponse>* AsyncsendAliveRequestRaw(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::AliveResponse>* PrepareAsyncsendAliveRequestRaw(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status sendAliveRequest(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::masterworker::AliveResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::AliveResponse>> AsyncsendAliveRequest(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::AliveResponse>>(AsyncsendAliveRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::AliveResponse>> PrepareAsyncsendAliveRequest(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::AliveResponse>>(PrepareAsyncsendAliveRequestRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::masterworker::AliveResponse>* AsyncsendAliveRequestRaw(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterworker::AliveResponse>* PrepareAsyncsendAliveRequestRaw(::grpc::ClientContext* context, const ::masterworker::AliveRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_sendAliveRequest_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Ping
    virtual ::grpc::Status sendAliveRequest(::grpc::ServerContext* context, const ::masterworker::AliveRequest* request, ::masterworker::AliveResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_sendAliveRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_sendAliveRequest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_sendAliveRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendAliveRequest(::grpc::ServerContext* context, const ::masterworker::AliveRequest* request, ::masterworker::AliveResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendAliveRequest(::grpc::ServerContext* context, ::masterworker::AliveRequest* request, ::grpc::ServerAsyncResponseWriter< ::masterworker::AliveResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_sendAliveRequest<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_sendAliveRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_sendAliveRequest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_sendAliveRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendAliveRequest(::grpc::ServerContext* context, const ::masterworker::AliveRequest* request, ::masterworker::AliveResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_sendAliveRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_sendAliveRequest() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_sendAliveRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendAliveRequest(::grpc::ServerContext* context, const ::masterworker::AliveRequest* request, ::masterworker::AliveResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendAliveRequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sendAliveRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_sendAliveRequest() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::masterworker::AliveRequest, ::masterworker::AliveResponse>(std::bind(&WithStreamedUnaryMethod_sendAliveRequest<BaseClass>::StreamedsendAliveRequest, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_sendAliveRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sendAliveRequest(::grpc::ServerContext* context, const ::masterworker::AliveRequest* request, ::masterworker::AliveResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsendAliveRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::masterworker::AliveRequest,::masterworker::AliveResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_sendAliveRequest<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_sendAliveRequest<Service > StreamedService;
};

}  // namespace masterworker


#endif  // GRPC_zk_2eproto__INCLUDED
