// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zk.proto

#include "zk.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace masterworker {
class AliveRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AliveRequest>
      _instance;
} _AliveRequest_default_instance_;
class AliveResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AliveResponse>
      _instance;
} _AliveResponse_default_instance_;
}  // namespace masterworker
namespace protobuf_zk_2eproto {
static void InitDefaultsAliveRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::masterworker::_AliveRequest_default_instance_;
    new (ptr) ::masterworker::AliveRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::masterworker::AliveRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AliveRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAliveRequest}, {}};

static void InitDefaultsAliveResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::masterworker::_AliveResponse_default_instance_;
    new (ptr) ::masterworker::AliveResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::masterworker::AliveResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AliveResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAliveResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_AliveRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_AliveResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::masterworker::AliveRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::masterworker::AliveRequest, alivequery_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::masterworker::AliveResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::masterworker::AliveResponse, reply_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::masterworker::AliveRequest)},
  { 6, -1, sizeof(::masterworker::AliveResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::masterworker::_AliveRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::masterworker::_AliveResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "zk.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\010zk.proto\022\014masterworker\"\"\n\014AliveRequest"
      "\022\022\n\naliveQuery\030\001 \001(\t\"\036\n\rAliveResponse\022\r\n"
      "\005reply\030\001 \001(\t2]\n\014MasterWorker\022M\n\020sendAliv"
      "eRequest\022\032.masterworker.AliveRequest\032\033.m"
      "asterworker.AliveResponse\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 195);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "zk.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_zk_2eproto
namespace masterworker {

// ===================================================================

void AliveRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AliveRequest::kAliveQueryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AliveRequest::AliveRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_zk_2eproto::scc_info_AliveRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:masterworker.AliveRequest)
}
AliveRequest::AliveRequest(const AliveRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  alivequery_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.alivequery().size() > 0) {
    alivequery_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.alivequery_);
  }
  // @@protoc_insertion_point(copy_constructor:masterworker.AliveRequest)
}

void AliveRequest::SharedCtor() {
  alivequery_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

AliveRequest::~AliveRequest() {
  // @@protoc_insertion_point(destructor:masterworker.AliveRequest)
  SharedDtor();
}

void AliveRequest::SharedDtor() {
  alivequery_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AliveRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AliveRequest::descriptor() {
  ::protobuf_zk_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zk_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AliveRequest& AliveRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_zk_2eproto::scc_info_AliveRequest.base);
  return *internal_default_instance();
}


void AliveRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:masterworker.AliveRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  alivequery_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool AliveRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:masterworker.AliveRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string aliveQuery = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_alivequery()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->alivequery().data(), static_cast<int>(this->alivequery().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "masterworker.AliveRequest.aliveQuery"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:masterworker.AliveRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:masterworker.AliveRequest)
  return false;
#undef DO_
}

void AliveRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:masterworker.AliveRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string aliveQuery = 1;
  if (this->alivequery().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->alivequery().data(), static_cast<int>(this->alivequery().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterworker.AliveRequest.aliveQuery");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->alivequery(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:masterworker.AliveRequest)
}

::google::protobuf::uint8* AliveRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:masterworker.AliveRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string aliveQuery = 1;
  if (this->alivequery().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->alivequery().data(), static_cast<int>(this->alivequery().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterworker.AliveRequest.aliveQuery");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->alivequery(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterworker.AliveRequest)
  return target;
}

size_t AliveRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterworker.AliveRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string aliveQuery = 1;
  if (this->alivequery().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->alivequery());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AliveRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:masterworker.AliveRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const AliveRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AliveRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:masterworker.AliveRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:masterworker.AliveRequest)
    MergeFrom(*source);
  }
}

void AliveRequest::MergeFrom(const AliveRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:masterworker.AliveRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.alivequery().size() > 0) {

    alivequery_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.alivequery_);
  }
}

void AliveRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:masterworker.AliveRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AliveRequest::CopyFrom(const AliveRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterworker.AliveRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AliveRequest::IsInitialized() const {
  return true;
}

void AliveRequest::Swap(AliveRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AliveRequest::InternalSwap(AliveRequest* other) {
  using std::swap;
  alivequery_.Swap(&other->alivequery_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AliveRequest::GetMetadata() const {
  protobuf_zk_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zk_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void AliveResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AliveResponse::kReplyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AliveResponse::AliveResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_zk_2eproto::scc_info_AliveResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:masterworker.AliveResponse)
}
AliveResponse::AliveResponse(const AliveResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  reply_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.reply().size() > 0) {
    reply_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reply_);
  }
  // @@protoc_insertion_point(copy_constructor:masterworker.AliveResponse)
}

void AliveResponse::SharedCtor() {
  reply_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

AliveResponse::~AliveResponse() {
  // @@protoc_insertion_point(destructor:masterworker.AliveResponse)
  SharedDtor();
}

void AliveResponse::SharedDtor() {
  reply_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AliveResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AliveResponse::descriptor() {
  ::protobuf_zk_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zk_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AliveResponse& AliveResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_zk_2eproto::scc_info_AliveResponse.base);
  return *internal_default_instance();
}


void AliveResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:masterworker.AliveResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reply_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool AliveResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:masterworker.AliveResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string reply = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reply()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reply().data(), static_cast<int>(this->reply().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "masterworker.AliveResponse.reply"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:masterworker.AliveResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:masterworker.AliveResponse)
  return false;
#undef DO_
}

void AliveResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:masterworker.AliveResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string reply = 1;
  if (this->reply().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reply().data(), static_cast<int>(this->reply().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterworker.AliveResponse.reply");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->reply(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:masterworker.AliveResponse)
}

::google::protobuf::uint8* AliveResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:masterworker.AliveResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string reply = 1;
  if (this->reply().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reply().data(), static_cast<int>(this->reply().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterworker.AliveResponse.reply");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->reply(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterworker.AliveResponse)
  return target;
}

size_t AliveResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterworker.AliveResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string reply = 1;
  if (this->reply().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reply());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AliveResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:masterworker.AliveResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const AliveResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AliveResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:masterworker.AliveResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:masterworker.AliveResponse)
    MergeFrom(*source);
  }
}

void AliveResponse::MergeFrom(const AliveResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:masterworker.AliveResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.reply().size() > 0) {

    reply_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reply_);
  }
}

void AliveResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:masterworker.AliveResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AliveResponse::CopyFrom(const AliveResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterworker.AliveResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AliveResponse::IsInitialized() const {
  return true;
}

void AliveResponse::Swap(AliveResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AliveResponse::InternalSwap(AliveResponse* other) {
  using std::swap;
  reply_.Swap(&other->reply_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AliveResponse::GetMetadata() const {
  protobuf_zk_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zk_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace masterworker
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::masterworker::AliveRequest* Arena::CreateMaybeMessage< ::masterworker::AliveRequest >(Arena* arena) {
  return Arena::CreateInternal< ::masterworker::AliveRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::masterworker::AliveResponse* Arena::CreateMaybeMessage< ::masterworker::AliveResponse >(Arena* arena) {
  return Arena::CreateInternal< ::masterworker::AliveResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
